name: Sandboxy
options:
  bundleIdPrefix: com.yll
  deploymentTarget:
    iOS: '17.0'

settings:
  base:
    SWIFT_VERSION: 5.0

targets:
  Sandboxy:
    type: application
    platform: iOS
    sources: [Sandboxy]
    bundleId: com.yll.Sandboxy
    deploymentTarget: '17.0'
    settings:
      base:
        CODE_SIGN_IDENTITY: Apple Development
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: H8X222M97N
    scheme:
      testTargets: []
